# Generated by Django 3.0.7 on 2020-06-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20200616_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='numViews',
            new_name='views',
        ),
    ]
