# Generated by Django 3.0.7 on 2020-06-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20200616_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='views',
        ),
        migrations.AddField(
            model_name='topic',
            name='numViews',
            field=models.IntegerField(default=0),
        ),
    ]
